function r = lab3_photo_analysis(p, outputDir)
% Static calibration and normalized response.

g = 9.80665;
kgPerLb = 0.45359237;
r.JD = p.mD * p.DD^2 / 8;
r.degPerLb = 360 / p.nominalLbPerRev;
r.forcePerRad = p.nominalLbPerRev * kgPerLb * g / (2*pi);
massLb = (0:1:p.nominalLbPerRev)';
forceN = massLb * kgPerLb * g;
thetaDeg = r.degPerLb * massLb;
r.nominal = table(massLb, forceN, thetaDeg, ...
    'VariableNames', {'IndicatedMass_lb','EquivalentForce_N','NominalDial_deg'});

%% Before/after readings
validateattributes(p.rawBaselineIndicationLb, {'numeric'}, ...
    {'row','numel',2,'real','finite'});
validateattributes(p.rawBaselineMidpointLb, {'numeric'}, ...
    {'scalar','real','finite'});
validateattributes(p.beforeIndicationLb, {'numeric'}, ...
    {'row','numel',2,'real','finite'});
validateattributes(p.afterIndicationLb, {'numeric'}, ...
    {'row','numel',2,'real','finite'});
stageRange = [p.beforeIndicationLb; p.afterIndicationLb];
assert(all(stageRange(:,2) >= stageRange(:,1)), ...
    'Lab3:ReadingRange', 'Reading interval endpoints must be ordered.');
baseline = p.rawBaselineIndicationLb;
baselineMidpoint = p.rawBaselineMidpointLb;
assert(baseline(1) <= baselineMidpoint && baselineMidpoint <= baseline(2), ...
    'Lab3:Baseline', 'Baseline midpoint must lie inside its reading interval.');
assert(isequal(p.loadedIndicationLb,p.afterIndicationLb), ...
    'Lab3:CalibrationStage', 'Static calibration must use the after-reassembly range.');
stageMidpoint = mean(stageRange,2);
netStageRange = [stageRange(:,1)-baseline(2),stageRange(:,2)-baseline(1)];
netStageMidpoint = stageMidpoint-baselineMidpoint;
netStageKg = netStageRange * kgPerLb;
r.beforeAfter = table(["Before disassembly";"After reassembly"], ...
    repmat(p.calibrationMassKg,2,1),repmat(baseline(1),2,1), ...
    repmat(baselineMidpoint,2,1),repmat(baseline(2),2,1), ...
    stageRange(:,1),stageMidpoint,stageRange(:,2), ...
    netStageRange(:,1),netStageMidpoint,netStageRange(:,2), ...
    netStageKg(:,1),netStageMidpoint*kgPerLb,netStageKg(:,2), ...
    repmat("Photo intervals; shared baseline; stage follows upload order",2,1), ...
    'VariableNames', {'Stage','NominalReferenceMass_kg', ...
    'RawBaselineLow_lb','RawBaselineMidpoint_lb','RawBaselineHigh_lb', ...
    'RawIndicationLow_lb','RawIndicationMidpoint_lb','RawIndicationHigh_lb', ...
    'NetIndicationLow_lb','NetIndicationMidpoint_lb','NetIndicationHigh_lb', ...
    'NetIndicatedMassLow_kg','NetIndicatedMassMidpoint_kg','NetIndicatedMassHigh_kg', ...
    'ReadingBasis'});
% Shared baseline cancels in the reading difference.
changeLb = [p.afterIndicationLb(1)-p.beforeIndicationLb(2), ...
    p.afterIndicationLb(2)-p.beforeIndicationLb(1)];
changeMidpoint = stageMidpoint(2)-stageMidpoint(1);
r.beforeAfterChange = table("After minus before",changeLb(1), ...
    changeMidpoint,changeLb(2),changeLb(1)*kgPerLb, ...
    changeMidpoint*kgPerLb,changeLb(2)*kgPerLb, ...
    "Shared baseline cancels; conservative photo bounds, not a confidence interval", ...
    'VariableNames', {'Comparison','ChangeLow_lb','MidpointChange_lb', ...
    'ChangeHigh_lb','ChangeLow_kg','MidpointChange_kg','ChangeHigh_kg','Basis'});
r.changeResolved = changeLb(1)>0 || changeLb(2)<0;

%% Static calibration
validateattributes(p.calibrationMassKg, {'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(p.loadedIndicationLb, {'numeric'}, ...
    {'vector','numel',2,'real','finite'});
assert(p.loadedIndicationLb(2) >= p.loadedIndicationLb(1) && ...
    p.loadedIndicationLb(1) > baseline(2), ...
    'Lab3:ReadingRange', 'Check the loaded and unloaded reading intervals.');
calForce = p.calibrationMassKg * g;
netRange = [p.loadedIndicationLb(1)-baseline(2), ...
    p.loadedIndicationLb(2)-baseline(1)];
netMidpoint = mean(p.loadedIndicationLb)-baselineMidpoint;
angleDeg = netRange * r.degPerLb;
angleMidpointDeg = netMidpoint*r.degPerLb;
angleRad = deg2rad(angleDeg);
angleMidpointRad = deg2rad(angleMidpointDeg);
sLow = angleRad(1) ./ calForce;
sMidpoint = angleMidpointRad ./ calForce;
sHigh = angleRad(2) ./ calForce;
kOverGammaLow = calForce / angleRad(2);
kOverGammaMidpoint = calForce / angleMidpointRad;
kOverGammaHigh = calForce / angleRad(1);
expectedNetLb = p.calibrationMassKg / kgPerLb;
expectedRawLb = baselineMidpoint + expectedNetLb;
massRatio = [netRange(1),netMidpoint,netRange(2)] * kgPerLb / p.calibrationMassKg;
n = numel(calForce);
r.staticCalibration = table(p.calibrationScenario, p.calibrationMassKg, ...
    calForce,repmat(baseline(1),n,1),repmat(baselineMidpoint,n,1),repmat(baseline(2),n,1), ...
    repmat(p.loadedIndicationLb(1),n,1), repmat(p.loadedIndicationLb(2),n,1), ...
    repmat(netRange(1),n,1),repmat(netMidpoint,n,1),repmat(netRange(2),n,1), ...
    repmat(angleDeg(1),n,1),repmat(angleMidpointDeg,n,1),repmat(angleDeg(2),n,1), ...
    repmat(angleRad(1),n,1),repmat(angleMidpointRad,n,1),repmat(angleRad(2),n,1), ...
    sLow,sMidpoint,sHigh,kOverGammaLow,kOverGammaMidpoint,kOverGammaHigh, ...
    expectedNetLb,expectedRawLb,massRatio(1),massRatio(2),massRatio(3), ...
    repmat("Apple nominal mass for the MacBook Air",n,1), ...
    repmat("After-reassembly raw reading minus shared photo baseline",n,1), ...
    p.calibrationMassSource, ...
    'VariableNames', {'Scenario','NominalMass_kg','Force_N', ...
    'RawBaselineLow_lb','RawBaselineMidpoint_lb','RawBaselineHigh_lb', ...
    'RawLoadedLow_lb','RawLoadedHigh_lb','NetLow_lb','NetMidpoint_lb','NetHigh_lb', ...
    'DeltaAngleLow_deg','DeltaAngleMidpoint_deg','DeltaAngleHigh_deg', ...
    'DeltaAngleLow_rad','DeltaAngleMidpoint_rad','DeltaAngleHigh_rad', ...
    'SThetaLow_rad_per_N','SThetaMidpoint_rad_per_N','SThetaHigh_rad_per_N', ...
    'KeqOverGammaLow_N_per_rad','KeqOverGammaMidpoint_N_per_rad','KeqOverGammaHigh_N_per_rad', ...
    'NominalExpectedNet_lb','NominalExpectedRaw_lb','NetMassRatioLow','NetMassRatioMidpoint','NetMassRatioHigh', ...
    'MassBasis','ReadingBasis','MassSource'});
assert(all(abs(sLow .* kOverGammaHigh - 1) < 1e-12) && ...
    all(abs(sHigh .* kOverGammaLow - 1) < 1e-12), ...
    'Lab3:StaticCalibration', 'Reciprocal interval check failed.');

%% Normalized step response
zeta = [0.2, 0.5, 1, 2];
tau = linspace(0, 30, 3001)';
y = zeros(numel(tau), numel(zeta));
overshoot = zeros(numel(zeta),1);
maxError = zeros(numel(zeta),1);
options = odeset('RelTol',1e-9, 'AbsTol',1e-11);
for k = 1:numel(zeta)
    z = zeta(k);
    [~, x] = ode45(@(t,x) [x(2); 1-2*z*x(2)-x(1)], tau, [0;0], options);
    y(:,k) = x(:,1);
    if z < 1
        wd = sqrt(1-z^2);
        exact = 1-exp(-z*tau).*(cos(wd*tau)+z/wd*sin(wd*tau));
        overshoot(k) = 100*exp(-pi*z/wd);
    elseif z == 1
        exact = 1-exp(-tau).*(1+tau);
    else
        r1 = -z+sqrt(z^2-1);
        r2 = -z-sqrt(z^2-1);
        exact = 1+(r2*exp(r1*tau)-r1*exp(r2*tau))/(r1-r2);
    end
    maxError(k) = max(abs(y(:,k)-exact));
end
r.normalized = array2table([tau,y], 'VariableNames', ...
    {'Tau','Zeta_0_2','Zeta_0_5','Zeta_1','Zeta_2'});
r.validation = table(zeta', overshoot, maxError, 'VariableNames', ...
    {'DampingRatio','AnalyticalOvershoot_pct','MaxODEError'});
assert(all(maxError < 1e-7), 'Lab3:ODESolution', 'ODE verification failed.');

%% Measurements
parameter = ["mU";"mD";"mS_total";"mAssembly";"mRetainer";"mRackSpring"; ...
    "DD";"retainerCoilLength";"rackFreeCoilLength";"rackInstalledCoilLength";"JD"];
value = [p.mU;p.mD;p.mS_total;p.mAssembly;p.mRetainer;p.mRackSpring; ...
    p.DD;p.retainerCoilLength;p.rackFreeCoilLength;p.rackInstalledCoilLength;r.JD];
unit = [repmat("kg",6,1);repmat("m",4,1);"kg*m^2"];
basis = [repmat("Balance display",6,1);repmat("Photo estimate",4,1);"Uniform thin disk"];
figureSource = ["25";"24";"23";"22";"21";"26";"20";"18";"19";"15";"20, 24"];
r.measurements = table(parameter,value,unit,basis,figureSource, ...
    'VariableNames', {'Parameter','Value_SI','Unit','Basis','DisassemblyFigure'});
fprintf('Static calibration: F = %.6g N; theta = %.6g deg.\n', ...
    calForce,angleMidpointDeg);
fprintf('Normalized ODE max error = %.3g.\n',max(maxError));

if strlength(string(outputDir)) == 0
    return
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end
writetable(r.measurements, fullfile(outputDir,'photo_measurements.csv'));
writetable(r.nominal, fullfile(outputDir,'nominal_dial.csv'));
writetable(r.staticCalibration, fullfile(outputDir,'static_calibration.csv'));
writetable(r.beforeAfter, fullfile(outputDir,'before_after_comparison.csv'));
writetable(r.beforeAfterChange, fullfile(outputDir,'before_after_change.csv'));
writetable(r.normalized, fullfile(outputDir,'normalized_response.csv'));
writetable(r.validation, fullfile(outputDir,'ode_validation.csv'));

%% Report figures
f = figure('Color','w','Name','Baseline-corrected calibration', ...
    'Units','inches','Position',[1 1 3.35 2.65]);
fitForce = linspace(0,1.08*max(calForce),201)';
colors = [0.10 0.36 0.68];
hold on;
bands = gobjects(n,1);
for k = 1:n
    lower = rad2deg(sLow(k)*fitForce);
    upper = rad2deg(sHigh(k)*fitForce);
    bands(k) = fill([fitForce;flipud(fitForce)], [lower;flipud(upper)], ...
        colors(k,:), 'FaceAlpha',0.22, 'EdgeColor','none');
    plot(fitForce,rad2deg(sMidpoint(k)*fitForce), 'Color',colors(k,:), ...
        'LineWidth',0.8, 'HandleVisibility','off');
    errorbar(calForce(k),angleMidpointDeg,angleMidpointDeg-angleDeg(1), ...
        angleDeg(2)-angleMidpointDeg, 'o', ...
        'Color',colors(k,:), 'MarkerFaceColor','w', 'MarkerSize',3.5, ...
        'LineWidth',1.1, 'CapSize',7, 'HandleVisibility','off');
end
nominalLine = plot(fitForce,rad2deg(fitForce/r.forcePerRad), ...
    'k--','LineWidth',1.1);
xlabel('Applied force (N)'); ylabel('Incremental dial rotation (deg)');
title('Baseline-corrected calibration');
legend([bands;nominalLine], ["Fitted range";"Nominal dial"], ...
    'Location','northwest','FontSize',7);
grid on; xlim([0 max(fitForce)]); ylim([0 1.08*rad2deg(max(sHigh)*max(fitForce))]);
set(gca,'FontName','Times New Roman','FontSize',8);
exportgraphics(f,fullfile(outputDir,'Fig17_Static_Calibration.png'),'Resolution',400);
savefig(f,fullfile(outputDir,'Fig17_Static_Calibration.fig'));

f = figure('Color','w','Name','Normalized damping response', ...
    'Units','inches','Position',[1 1 3.35 2.6]);
styles = {'-','--','-.',':'};
for k = 1:numel(zeta)
    plot(tau,y(:,k),styles{k},'LineWidth',1.15); hold on;
end
yline(1,'k:','HandleVisibility','off');
xlabel('Normalized time, \tau = \omega_n t');
ylabel('Normalized angle, \theta / \theta_{ss}');
title('Damping-ratio sensitivity');
legend('\zeta = 0.2','\zeta = 0.5','\zeta = 1','\zeta = 2', ...
    'Location','northeast');
grid on; xlim([0 30]); ylim([0 1.65]);
set(gca,'FontName','Times New Roman','FontSize',8);
exportgraphics(f,fullfile(outputDir,'Fig18_Normalized_Response.png'),'Resolution',400);
savefig(f,fullfile(outputDir,'Fig18_Normalized_Response.fig'));
end
